# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6f071384abc3f442dc5b03983480cb5fe4dc190813f0099179f36cea5daa7c8500892981c93e5aa3c88a25ad1f7a27abbc2416b9536760c39bd92464a2f23a9

test:
  secret_key_base: e6bb783e2fdd83540ec3a2ca9560faafd0469d991429712142033e75e8f8a04118b961eb8eb6308a46821520358353208cc0617a6ee51bdfd51c5b3db25c351d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
